wandb_version: 1

project_name:
  desc: null
  value: wandb_demo
batch_size:
  desc: null
  value: 512
hidden_layer_width:
  desc: null
  value: 64
dropout_p:
  desc: null
  value: 0.1
lr:
  desc: null
  value: 0.0001
optim_type:
  desc: null
  value: Adam
epochs:
  desc: null
  value: 15
ckpt_path:
  desc: null
  value: checkpoint.pt
_wandb:
  desc: null
  value:
    python_version: 3.8.16
    cli_version: 0.15.11
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1697039406.09649
    t:
      1:
      - 1
      - 41
      - 55
      - 105
      2:
      - 1
      - 41
      - 55
      - 105
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.8.16
      5: 0.15.11
      8:
      - 1
      - 4
      - 5
      13: darwin-arm64
    session_history: code/_session_history.ipynb
