wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.16
    cli_version: 0.15.11
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1697040705.888667
    t:
      1:
      - 1
      - 41
      - 55
      - 105
      2:
      - 1
      - 41
      - 55
      - 105
      3:
      - 2
      - 5
      - 14
      - 23
      4: 3.8.16
      5: 0.15.11
      8:
      - 1
      - 4
      - 5
      13: darwin-arm64
lr:
  desc: null
  value: 0.0001
epochs:
  desc: null
  value: 15
ckpt_path:
  desc: null
  value: checkpoint.pt
dropout_p:
  desc: null
  value: 0.1
batch_size:
  desc: null
  value: 512
optim_type:
  desc: null
  value: Adam
project_name:
  desc: null
  value: wandb_demo
hidden_layer_width:
  desc: null
  value: 64
